version: "3"
services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  redis:
    image: redis
    ports:
      - "6379:6379"
  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && ./bin/dev"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
volumes:
  mongodb_data:
